import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-white text-lg font-bold">CareerVerve</Link>
            <div>
              <Link href="/resumes" className="text-gray-300 hover:text-white mr-4">Resume Builder</Link>
              <Link href="/jd-match" className="text-gray-300 hover:text-white">JD Match</Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
